# -*- coding: utf-8 -*-
"""Flights Seoul

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13FM2qK0AaytmX99DeuwRcttbFVCBPWUq
"""

# Commented out IPython magic to ensure Python compatibility.
#Libraries download
# %pip install requests

#Libraries import
import requests
import json
import smtplib
import ssl

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def jprint(obj):
    # create a formatted string of the Python JSON object
    text = json.dumps(obj, sort_keys=True, indent=4)
    print(text)

#Variables init
apikey = "63a6ce6749594391ceba35f7"
departureIATA = "GVA"
arrivalIATA = "ICN"
departureDate = "2023-03-23"
returnDate = "2023-04-01"
numberofAdults = 1
cabinClass = "Economy"
Currency = "CHF"

#Api Call
response = requests.get(f"https://api.flightapi.io/roundtrip/{apikey}/{departureIATA}/{arrivalIATA}/{departureDate}/{returnDate}/{numberofAdults}/0/0/{cabinClass}/{Currency}")

objJSON = json.loads(response.text)
prices = []
for fare in objJSON['fares']:
    if fare["providerCode"] == "etihad.com":
      prices.append(fare["price"]["totalAmount"])
      
minimumfare = min(prices)

#sendEmail
port = 587  # For SSL
password = "pUi33$*nf&xsbeg%"
smtp_server = "mail.infomaniak.com"

msg = MIMEMultipart('alternative')
msg['Subject'] = "Flight Price Update - Seoul"
msg['From'] = "api@hfamily.ch"
msg['To'] = "yassin@hfamily.ch"

# Create the body of the message (a plain-text and an HTML version).
text = """
Salut pour la 100'0000'000x aujourd'hui, voici les dernière nouvelles:<br>
        Aéroport de départ: GVA<br>
        Aéroport d'arrivée: SEL<br>
        Date de départ: 2022-03-23<br>
        Date d'arrivée: 2022-04-01<br>
        Prix tolal A/R: {minimumfare} CHF<br>
        Compagnie aérienne: etihad.com<br>
        Remboursable?: FALSE<br>
<br>
        A dans une heure :)<br>
        Provided by Hfamily API"""
html = f"""\
<html>
  <head></head>
  <body>
    <p>Salut pour la 100'0000'000x aujourd'hui, voici les dernière nouvelles:<br>
        Aéroport de départ: GVA<br>
        Aéroport d'arrivée: SEL<br>
        Date de départ: 2022-03-23<br>
        Date d'arrivée: 2022-04-01<br>
        Prix tolal A/R: <b>{minimumfare}</b> CHF<br>
        Compagnie aérienne: etihad.com<br>
        Remboursable?: FALSE<br>

        A dans une heure :)<br>
        Provided by Hfamily API
    </p>
  </body>
</html>
"""

part1 = MIMEText(text, 'plain')
part2 = MIMEText(html, 'html')


msg.attach(part1)
msg.attach(part2)



context = ssl.create_default_context()
with smtplib.SMTP(smtp_server, port) as server:
    server.ehlo()  # Can be omitted
    server.starttls(context=context)
    server.ehlo()  # Can be omitted
    server.login("api@hfamily.ch", password)
    server.sendmail("api@hfamily.ch", msg['To'], msg.as_string())
