# -*- coding: utf-8 -*-
"""Flights Seoul

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13FM2qK0AaytmX99DeuwRcttbFVCBPWUq
"""

# Commented out IPython magic to ensure Python compatibility.
#Libraries download
# %pip install requests

#Libraries import
import requests
import json
import smtplib
import ssl
import pandas as pd
import datetime
import os.path

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from matplotlib import pyplot as plt

def jprint(obj):
    # create a formatted string of the Python JSON object
    text = json.dumps(obj, sort_keys=True, indent=4)
    print(text)

#Variables init
apikey = "63a6ce6749594391ceba35f7"
departureIATA = "GVA"
arrivalIATA = "ICN"
departureDate = "2023-03-23"
returnDate = "2023-04-01"
numberofAdults = 1
cabinClass = "Economy"
Currency = "CHF"
path_csv = "/content/sample_data/"
path_images = "/content/sample_data/"

#Api Call
response = requests.get(f"https://api.flightapi.io/roundtrip/{apikey}/{departureIATA}/{arrivalIATA}/{departureDate}/{returnDate}/{numberofAdults}/0/0/{cabinClass}/{Currency}")

objJSON = json.loads(response.text)
prices = []
Etihad_prices = []
for fare in objJSON['fares']:
    if fare["providerCode"] == "etihad.com":
      prices.append(fare["price"]["totalAmount"])
      
Etihad_prices.append([datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Etihad", min(prices)])
Etihad_price_history = pd.DataFrame(Etihad_prices, columns=['Timestamp', 'Airline', 'Price'])
if(os.path.isfile(f'{path_csv}EtihadPrices.csv')):
    Etihad_price_history.to_csv(f'{path_csv}EtihadPrices.csv',  header=False, mode='a')
else:
   Etihad_price_history.to_csv(f'{path_csv}EtihadPrices.csv')      
minimumfare = min(prices)

tendancy = ""
df = pd.read_csv(f'{path_csv}EtihadPrices.csv')
try:
  previousprice = df.iloc[-2]
except:
  #One or no rows in the CSV file
  previousprice = df.iloc[-1]
previousprice
if minimumfare == int(previousprice["Price"]):
 tendancy = "&#8594;"
if minimumfare > int(previousprice["Price"]):
  tendancy = "&#8600;"
if minimumfare < int(previousprice["Price"]):
  tendancy = "&#8599;"

import datetime
airlinemame = ""
airlines = []
for filter in objJSON['filters']['airlines']:
  for code in objJSON['airlines']:
    if filter['code'] == code['code']:
      airlinemame = code['name']
  airlines.append([datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"), airlinemame, filter['price']['totalAmount']])

airlinesDataFrame = pd.DataFrame(airlines, columns=['Timestamp', 'Airline', 'Price'])
if(os.path.isfile(f'{path_csv}airlinesPrices.csv')):
    airlinesDataFrame.to_csv(f'{path_csv}airlinesPrices.csv',  header=False, mode='a')
else:
   airlinesDataFrame.to_csv(f'{path_csv}airlinesPrices.csv')

imagesrc =f"{path_images}{datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_airlinesPrices.png"
plt.rcParams["figure.figsize"] = [10, 5]
plt.rcParams["figure.autolayout"] = True
columns = ["Timestamp", "Airline", "Price"]
df = pd.read_csv(f'{path_csv}airlinesPrices.csv')
grouped_airlines = df.groupby(['Airline'])

for airline, rows in grouped_airlines:
  plt.step(rows["Timestamp"], rows["Price"], label = airline)

plt.legend(loc="upper right")
plt.savefig(imagesrc)

imagesrcethiad =f"{path_images}{datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_EthiadPrices.png"
plt.rcParams["figure.figsize"] = [10, 5]
plt.rcParams["figure.autolayout"] = True
columns = ["Timestamp", "Airline", "Price"]
df = pd.read_csv(f'{path_csv}airlinesPrices.csv')
grouped_airlines = df.groupby(['Airline'])

for airline, rows in grouped_airlines:
  if airline == "Etihad Airways":
    plt.step(rows["Timestamp"], rows["Price"], label = airline)

plt.legend(loc="upper right")
plt.savefig(imagesrcethiad)



#sendEmail
port = 587  # For SSL
password = "pUi33$*nf&xsbeg%"
smtp_server = "mail.infomaniak.com"

msg = MIMEMultipart('alternative')
msg['Subject'] = "Flight Price Update - Seoul"
msg['From'] = "api@hfamily.ch"
msg['To'] = "hediger.yassin@gmail.com"

# Create the body of the message (a plain-text and an HTML version).
html = """
<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--[if IE]><html xmlns="http://www.w3.org/1999/xhtml" class="ie"><![endif]-->
<!--[if !IE]><!-->
<html style="margin: 0;padding: 0;" xmlns="http://www.w3.org/1999/xhtml">
<!--<![endif]-->

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title></title>
  <!--[if !mso]><!-->
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!--<![endif]-->
  <meta name="viewport" content="width=device-width" />
  <style type="text/css">
    @media only screen and (min-width: 620px) {
      .wrapper {
        min-width: 600px !important
      }

      .wrapper h1 {}

      .wrapper h1 {
        font-size: 26px !important;
        line-height: 34px !important
      }

      .wrapper h2 {}

      .wrapper h2 {
        font-size: 20px !important;
        line-height: 28px !important
      }

      .wrapper h3 {}

      .column {}

      .wrapper .size-8 {
        font-size: 8px !important;
        line-height: 14px !important
      }

      .wrapper .size-9 {
        font-size: 9px !important;
        line-height: 16px !important
      }

      .wrapper .size-10 {
        font-size: 10px !important;
        line-height: 18px !important
      }

      .wrapper .size-11 {
        font-size: 11px !important;
        line-height: 19px !important
      }

      .wrapper .size-12 {
        font-size: 12px !important;
        line-height: 19px !important
      }

      .wrapper .size-13 {
        font-size: 13px !important;
        line-height: 21px !important
      }

      .wrapper .size-14 {
        font-size: 14px !important;
        line-height: 21px !important
      }

      .wrapper .size-15 {
        font-size: 15px !important;
        line-height: 23px !important
      }

      .wrapper .size-16 {
        font-size: 16px !important;
        line-height: 24px !important
      }

      .wrapper .size-17 {
        font-size: 17px !important;
        line-height: 26px !important
      }

      .wrapper .size-18 {
        font-size: 18px !important;
        line-height: 26px !important
      }

      .wrapper .size-20 {
        font-size: 20px !important;
        line-height: 28px !important
      }

      .wrapper .size-22 {
        font-size: 22px !important;
        line-height: 31px !important
      }

      .wrapper .size-24 {
        font-size: 24px !important;
        line-height: 32px !important
      }

      .wrapper .size-26 {
        font-size: 26px !important;
        line-height: 34px !important
      }

      .wrapper .size-28 {
        font-size: 28px !important;
        line-height: 36px !important
      }

      .wrapper .size-30 {
        font-size: 30px !important;
        line-height: 38px !important
      }

      .wrapper .size-32 {
        font-size: 32px !important;
        line-height: 40px !important
      }

      .wrapper .size-34 {
        font-size: 34px !important;
        line-height: 43px !important
      }

      .wrapper .size-36 {
        font-size: 36px !important;
        line-height: 43px !important
      }

      .wrapper .size-40 {
        font-size: 40px !important;
        line-height: 47px !important
      }

      .wrapper .size-44 {
        font-size: 44px !important;
        line-height: 50px !important
      }

      .wrapper .size-48 {
        font-size: 48px !important;
        line-height: 54px !important
      }

      .wrapper .size-56 {
        font-size: 56px !important;
        line-height: 60px !important
      }

      .wrapper .size-64 {
        font-size: 64px !important;
        line-height: 68px !important
      }

      .wrapper .size-72 {
        font-size: 72px !important;
        line-height: 76px !important
      }

      .wrapper .size-80 {
        font-size: 80px !important;
        line-height: 84px !important
      }

      .wrapper .size-96 {
        font-size: 96px !important;
        line-height: 100px !important
      }

      .wrapper .size-112 {
        font-size: 112px !important;
        line-height: 116px !important
      }

      .wrapper .size-128 {
        font-size: 128px !important;
        line-height: 132px !important
      }

      .wrapper .size-144 {
        font-size: 144px !important;
        line-height: 148px !important
      }
    }
  </style>
  <meta name="x-apple-disable-message-reformatting" />
  <style type="text/css">
    .main,
    .mso {
      margin: 0;
      padding: 0;
    }

    table {
      border-collapse: collapse;
      table-layout: fixed;
    }

    * {
      line-height: inherit;
    }

    [x-apple-data-detectors] {
      color: inherit !important;
      text-decoration: none !important;
    }

    .wrapper .footer__share-button a:hover,
    .wrapper .footer__share-button a:focus {
      color: #ffffff !important;
    }

    .wrapper .footer__share-button a.icon-white:hover,
    .wrapper .footer__share-button a.icon-white:focus {
      color: #ffffff !important;
    }

    .wrapper .footer__share-button a.icon-black:hover,
    .wrapper .footer__share-button a.icon-black:focus {
      color: #000000 !important;
    }

    .btn a:hover,
    .btn a:focus,
    .footer__share-button a:hover,
    .footer__share-button a:focus,
    .email-footer__links a:hover,
    .email-footer__links a:focus {
      opacity: 0.8;
    }

    .preheader,
    .header,
    .layout,
    .column {
      transition: width 0.25s ease-in-out, max-width 0.25s ease-in-out;
    }

    .preheader td {
      padding-bottom: 8px;
    }

    .layout,
    div.header {
      max-width: 400px !important;
      -fallback-width: 95% !important;
      width: calc(100% - 20px) !important;
    }

    div.preheader {
      max-width: 360px !important;
      -fallback-width: 90% !important;
      width: calc(100% - 60px) !important;
    }

    .snippet,
    .webversion {
      Float: none !important;
    }

    .stack .column {
      max-width: 400px !important;
      width: 100% !important;
    }

    .fixed-width.has-border {
      max-width: 402px !important;
    }

    .fixed-width.has-border .layout__inner {
      box-sizing: border-box;
    }

    .snippet,
    .webversion {
      width: 50% !important;
    }

    .ie .btn {
      width: 100%;
    }

    .ie .stack .column,
    .ie .stack .gutter {
      display: table-cell;
      float: none !important;
    }

    .ie div.preheader,
    .ie .email-footer {
      max-width: 560px !important;
      width: 560px !important;
    }

    .ie .snippet,
    .ie .webversion {
      width: 280px !important;
    }

    .ie div.header,
    .ie .layout {
      max-width: 600px !important;
      width: 600px !important;
    }

    .ie .two-col .column {
      max-width: 300px !important;
      width: 300px !important;
    }

    .ie .three-col .column,
    .ie .narrow {
      max-width: 200px !important;
      width: 200px !important;
    }

    .ie .wide {
      width: 400px !important;
    }

    .ie .stack.fixed-width.has-border,
    .ie .stack.has-gutter.has-border {
      max-width: 602px !important;
      width: 602px !important;
    }

    .ie .stack.two-col.has-gutter .column {
      max-width: 290px !important;
      width: 290px !important;
    }

    .ie .stack.three-col.has-gutter .column,
    .ie .stack.has-gutter .narrow {
      max-width: 188px !important;
      width: 188px !important;
    }

    .ie .stack.has-gutter .wide {
      max-width: 394px !important;
      width: 394px !important;
    }

    .ie .stack.two-col.has-gutter.has-border .column {
      max-width: 292px !important;
      width: 292px !important;
    }

    .ie .stack.three-col.has-gutter.has-border .column,
    .ie .stack.has-gutter.has-border .narrow {
      max-width: 190px !important;
      width: 190px !important;
    }

    .ie .stack.has-gutter.has-border .wide {
      max-width: 396px !important;
      width: 396px !important;
    }

    .ie .fixed-width .layout__inner {
      border-left: 0 none white !important;
      border-right: 0 none white !important;
    }

    .ie .layout__edges {
      display: none;
    }

    .mso .layout__edges {
      font-size: 0;
    }

    .layout-fixed-width,
    .mso .layout-full-width {
      background-color: #ffffff;
    }

    @media only screen and (min-width: 620px) {

      .column,
      .gutter {
        display: table-cell;
        Float: none !important;
        vertical-align: top;
      }

      div.preheader,
      .email-footer {
        max-width: 560px !important;
        width: 560px !important;
      }

      .snippet,
      .webversion {
        width: 280px !important;
      }

      div.header,
      .layout,
      .one-col .column {
        max-width: 600px !important;
        width: 600px !important;
      }

      .fixed-width.has-border,
      .fixed-width.x_has-border,
      .has-gutter.has-border,
      .has-gutter.x_has-border {
        max-width: 602px !important;
        width: 602px !important;
      }

      .two-col .column {
        max-width: 300px !important;
        width: 300px !important;
      }

      .three-col .column,
      .column.narrow,
      .column.x_narrow {
        max-width: 200px !important;
        width: 200px !important;
      }

      .column.wide,
      .column.x_wide {
        width: 400px !important;
      }

      .two-col.has-gutter .column,
      .two-col.x_has-gutter .column {
        max-width: 290px !important;
        width: 290px !important;
      }

      .three-col.has-gutter .column,
      .three-col.x_has-gutter .column,
      .has-gutter .narrow {
        max-width: 188px !important;
        width: 188px !important;
      }

      .has-gutter .wide {
        max-width: 394px !important;
        width: 394px !important;
      }

      .two-col.has-gutter.has-border .column,
      .two-col.x_has-gutter.x_has-border .column {
        max-width: 292px !important;
        width: 292px !important;
      }

      .three-col.has-gutter.has-border .column,
      .three-col.x_has-gutter.x_has-border .column,
      .has-gutter.has-border .narrow,
      .has-gutter.x_has-border .narrow {
        max-width: 190px !important;
        width: 190px !important;
      }

      .has-gutter.has-border .wide,
      .has-gutter.x_has-border .wide {
        max-width: 396px !important;
        width: 396px !important;
      }
    }

    @supports (display: flex) {
      @media only screen and (min-width: 620px) {
        .fixed-width.has-border .layout__inner {
          display: flex !important;
        }
      }
    }

    /***
* Mobile Styles
*
* 1. Overriding inline styles
*/

    @media(max-width: 619px) {

      .email-flexible-footer .left-aligned-footer .column,
      .email-flexible-footer .center-aligned-footer,
      .email-flexible-footer .right-aligned-footer .column {
        max-width: 100% !important;
        /* [1] */
        text-align: center !important;
        /* [1] */
        width: 100% !important;
        /* [1] */
      }

      .flexible-footer-logo {
        margin-left: 0px !important;
        /* [1] */
        margin-right: 0px !important;
        /* [1] */
      }

      .email-flexible-footer .left-aligned-footer .flexible-footer__share-button__container,
      .email-flexible-footer .center-aligned-footer .flexible-footer__share-button__container,
      .email-flexible-footer .right-aligned-footer .flexible-footer__share-button__container {
        display: inline-block;
        margin-left: 5px !important;
        /* [1] */
        margin-right: 5px !important;
        /* [1] */
      }

      .email-flexible-footer__additionalinfo--center {
        text-align: center !important;
        /* [1] */
      }

      .email-flexible-footer .left-aligned-footer table,
      .email-flexible-footer .center-aligned-footer table,
      .email-flexible-footer .right-aligned-footer table {
        display: table !important;
        /* [1] */
        width: 100% !important;
        /* [1] */
      }

      .email-flexible-footer .footer__share-button,
      .email-flexible-footer .email-footer__additional-info {
        margin-left: 20px;
        margin-right: 20px;
      }
    }

    @media only screen and (-webkit-min-device-pixel-ratio: 2),
    only screen and (min--moz-device-pixel-ratio: 2),
    only screen and (-o-min-device-pixel-ratio: 2/1),
    only screen and (min-device-pixel-ratio: 2),
    only screen and (min-resolution: 192dpi),
    only screen and (min-resolution: 2dppx) {
      .fblike {
        background-image: url(https://i7.createsend1.com/static/eb/master/13-the-blueprint-3/images/fblike@2x.png) !important;
      }

      .tweet {
        background-image: url(https://i8.createsend1.com/static/eb/master/13-the-blueprint-3/images/tweet@2x.png) !important;
      }

      .linkedinshare {
        background-image: url(https://i9.createsend1.com/static/eb/master/13-the-blueprint-3/images/lishare@2x.png) !important;
      }

      .forwardtoafriend {
        background-image: url(https://i10.createsend1.com/static/eb/master/13-the-blueprint-3/images/forward@2x.png) !important;
      }
    }

    @media (max-width: 321px) {
      .fixed-width.has-border .layout__inner {
        border-width: 1px 0 !important;
      }

      .layout,
      .stack .column {
        min-width: 320px !important;
        width: 320px !important;
      }

      .border {
        display: none;
      }

      .has-gutter .border {
        display: table-cell;
      }
    }

    .mso div {
      border: 0 none white !important;
    }

    .mso .w560 .divider {
      Margin-left: 260px !important;
      Margin-right: 260px !important;
    }

    .mso .w360 .divider {
      Margin-left: 160px !important;
      Margin-right: 160px !important;
    }

    .mso .w260 .divider {
      Margin-left: 110px !important;
      Margin-right: 110px !important;
    }

    .mso .w160 .divider {
      Margin-left: 60px !important;
      Margin-right: 60px !important;
    }

    .mso .w354 .divider {
      Margin-left: 157px !important;
      Margin-right: 157px !important;
    }

    .mso .w250 .divider {
      Margin-left: 105px !important;
      Margin-right: 105px !important;
    }

    .mso .w148 .divider {
      Margin-left: 54px !important;
      Margin-right: 54px !important;
    }

    .mso .size-8,
    .ie .size-8 {
      font-size: 8px !important;
      line-height: 14px !important;
    }

    .mso .size-9,
    .ie .size-9 {
      font-size: 9px !important;
      line-height: 16px !important;
    }

    .mso .size-10,
    .ie .size-10 {
      font-size: 10px !important;
      line-height: 18px !important;
    }

    .mso .size-11,
    .ie .size-11 {
      font-size: 11px !important;
      line-height: 19px !important;
    }

    .mso .size-12,
    .ie .size-12 {
      font-size: 12px !important;
      line-height: 19px !important;
    }

    .mso .size-13,
    .ie .size-13 {
      font-size: 13px !important;
      line-height: 21px !important;
    }

    .mso .size-14,
    .ie .size-14 {
      font-size: 14px !important;
      line-height: 21px !important;
    }

    .mso .size-15,
    .ie .size-15 {
      font-size: 15px !important;
      line-height: 23px !important;
    }

    .mso .size-16,
    .ie .size-16 {
      font-size: 16px !important;
      line-height: 24px !important;
    }

    .mso .size-17,
    .ie .size-17 {
      font-size: 17px !important;
      line-height: 26px !important;
    }

    .mso .size-18,
    .ie .size-18 {
      font-size: 18px !important;
      line-height: 26px !important;
    }

    .mso .size-20,
    .ie .size-20 {
      font-size: 20px !important;
      line-height: 28px !important;
    }

    .mso .size-22,
    .ie .size-22 {
      font-size: 22px !important;
      line-height: 31px !important;
    }

    .mso .size-24,
    .ie .size-24 {
      font-size: 24px !important;
      line-height: 32px !important;
    }

    .mso .size-26,
    .ie .size-26 {
      font-size: 26px !important;
      line-height: 34px !important;
    }

    .mso .size-28,
    .ie .size-28 {
      font-size: 28px !important;
      line-height: 36px !important;
    }

    .mso .size-30,
    .ie .size-30 {
      font-size: 30px !important;
      line-height: 38px !important;
    }

    .mso .size-32,
    .ie .size-32 {
      font-size: 32px !important;
      line-height: 40px !important;
    }

    .mso .size-34,
    .ie .size-34 {
      font-size: 34px !important;
      line-height: 43px !important;
    }

    .mso .size-36,
    .ie .size-36 {
      font-size: 36px !important;
      line-height: 43px !important;
    }

    .mso .size-40,
    .ie .size-40 {
      font-size: 40px !important;
      line-height: 47px !important;
    }

    .mso .size-44,
    .ie .size-44 {
      font-size: 44px !important;
      line-height: 50px !important;
    }

    .mso .size-48,
    .ie .size-48 {
      font-size: 48px !important;
      line-height: 54px !important;
    }

    .mso .size-56,
    .ie .size-56 {
      font-size: 56px !important;
      line-height: 60px !important;
    }

    .mso .size-64,
    .ie .size-64 {
      font-size: 64px !important;
      line-height: 68px !important;
    }

    .mso .size-72,
    .ie .size-72 {
      font-size: 72px !important;
      line-height: 76px !important;
    }

    .mso .size-80,
    .ie .size-80 {
      font-size: 80px !important;
      line-height: 84px !important;
    }

    .mso .size-96,
    .ie .size-96 {
      font-size: 96px !important;
      line-height: 100px !important;
    }

    .mso .size-112,
    .ie .size-112 {
      font-size: 112px !important;
      line-height: 116px !important;
    }

    .mso .size-128,
    .ie .size-128 {
      font-size: 128px !important;
      line-height: 132px !important;
    }

    .mso .size-144,
    .ie .size-144 {
      font-size: 144px !important;
      line-height: 148px !important;
    }

    /***
* Online store block styles
*
* 1. maintaining right and left margins in outlook
* 2. respecting line-height for tds in outlook
*/

    .mso .cmctbl table td,
    .mso .cmctbl table th {
      Margin-left: 20px !important;
      /* [1] */
      Margin-right: 20px !important;
      /* [1] */
    }

    .cmctbl--inline table {
      border-collapse: collapse;
    }

    .mso .cmctbl--inline table,
    .mso .cmctbl table {
      mso-table-lspace: 0pt;
      mso-table-rspace: 0pt;
      mso-line-height-rule: exactly;
      /* [2] */
    }
  </style>

  <!--[if !mso]><!-->
  <style type="text/css">
    @import url(https://fonts.googleapis.com/css?family=Ubuntu:400,700,400italic,700italic);
  </style>
  <link href="https://fonts.googleapis.com/css?family=Ubuntu:400,700,400italic,700italic" rel="stylesheet"
    type="text/css" />
  <!--<![endif]-->
  <style type="text/css">
    .main,
    .mso {
      background-color: #fbfbfb
    }

    .logo a:hover,
    .logo a:focus {
      color: #1e2e3b !important
    }

    .footer-logo a:hover,
    .footer-logo a:focus {
      color: #372d1b !important
    }

    .mso .layout-has-border {
      border-top: 1px solid #c8c8c8;
      border-bottom: 1px solid #c8c8c8
    }

    .mso .layout-has-bottom-border {
      border-bottom: 1px solid #c8c8c8
    }

    .mso .border,
    .ie .border {
      background-color: #c8c8c8
    }

    .mso h1,
    .ie h1 {}

    .mso h1,
    .ie h1 {
      font-size: 26px !important;
      line-height: 34px !important
    }

    .mso h2,
    .ie h2 {}

    .mso h2,
    .ie h2 {
      font-size: 20px !important;
      line-height: 28px !important
    }

    .mso h3,
    .ie h3 {}

    .mso .layout__inner,
    .ie .layout__inner {}

    .mso .footer__share-button p {}

    .mso .footer__share-button p {
      font-family: Georgia, serif
    }
  </style>
  <meta name="robots" content="noindex,nofollow" />
  <meta property="og:title" content="My First Campaign" />
</head>
<!--[if mso]>
  <body class="mso">
<![endif]-->
<!--[if !mso]><!-->

<body class="main full-padding" style="margin: 0;padding: 0;-webkit-text-size-adjust: 100%;">
  <!--<![endif]-->
  <table class="wrapper"
    style="border-collapse: collapse;table-layout: fixed;min-width: 320px;width: 100%;background-color: #fbfbfb;"
    cellpadding="0" cellspacing="0" role="presentation">
    <tbody>
      <tr>
        <td>
          <div role="banner">
            <div class="preheader"
              style="Margin: 0 auto;max-width: 560px;min-width: 280px; width: 280px;width: calc(28000% - 167440px);">
              <div style="border-collapse: collapse;display: table;width: 100%;">
                <!--[if (mso)|(IE)]><table align="center" class="preheader" cellpadding="0" cellspacing="0" role="presentation"><tr><td style="width: 280px" valign="top"><![endif]-->
                <div class="snippet"
                  style="display: table-cell;Float: left;font-size: 12px;line-height: 19px;max-width: 280px;min-width: 140px; width: 140px;width: calc(14000% - 78120px);padding: 10px 0 5px 0;color: #999;font-family: Georgia,serif;">

                </div>
                <!--[if (mso)|(IE)]></td><td style="width: 280px" valign="top"><![endif]-->
                <div class="webversion"
                  style="display: table-cell;Float: left;font-size: 12px;line-height: 19px;max-width: 280px;min-width: 139px; width: 139px;width: calc(14100% - 78680px);padding: 10px 0 5px 0;text-align: right;color: #999;font-family: Georgia,serif;">

                </div>
                <!--[if (mso)|(IE)]></td></tr></table><![endif]-->
              </div>
            </div>

          </div>
          <div>
            <div class="layout one-col fixed-width stack"
              style="Margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;">
              <div class="layout__inner"
                style="border-collapse: collapse;display: table;width: 100%;background-color: #ffffff;">
                <!--[if (mso)|(IE)]><table align="center" cellpadding="0" cellspacing="0" role="presentation"><tr class="layout-fixed-width" style="background-color: #ffffff;"><td style="width: 600px" class="w560"><![endif]-->
                <div class="column"
                  style="text-align: left;color: #565656;font-size: 14px;line-height: 21px;font-family: Georgia,serif;">

                  <div style="Margin-left: 20px;Margin-right: 20px;Margin-top: 24px;">
                    <div style="mso-line-height-rule: exactly;mso-text-raise: 11px;vertical-align: middle;">
                      <h1 class="size-22"
                        style="Margin-top: 0;Margin-bottom: 0;font-style: normal;font-weight: normal;color: #565656;font-size: 18px;line-height: 26px;font-family: Ubuntu,sans-serif;"
                        lang="x-size-22">
                        <span class="font-ubuntu" style="text-decoration: inherit;">
                          <span style="text-decoration: inherit;">Bien le bonjour Rapha&#235;l,</span>
                        </span>
                      </h1>
                      <p style="Margin-top: 20px;Margin-bottom: 0;font-family: Ubuntu,sans-serif;">
                        <span class="font-ubuntu" style="text-decoration: inherit;"><span
                            style="text-decoration: inherit;">Comme d'habitude, voici ton rapport r&#233;gulier
                            concernant le prix des vols pour partir avec nous &#224; S&#233;oul. On t'aime
                          </span></span>
                      </p>
                      <h2 class="size-17"
                        style="Margin-top: 20px;Margin-bottom: 0;font-style: normal;font-weight: normal;color: #555;font-size: 17px;line-height: 26px;font-family: Ubuntu,sans-serif;"
                        lang="x-size-17"><span class="font-ubuntu" style="text-decoration: inherit;"><span
                            style="text-decoration: inherit;">Informations du Voyage:</span></span>
                      </h2>
                      <ul style="Margin-top: 16px;Margin-bottom: 0;Margin-left: 24px;padding: 0;list-style-type: disc;">
                        <li style="Margin-top: 16px;Margin-bottom: 0;Margin-left: 0;font-family: Ubuntu,sans-serif;">
                          <span class="font-ubuntu" style="text-decoration: inherit;"><span
                              style="text-decoration: inherit;">A&#233;roport de d&#233;part: GVA</span></span>
                        </li>
                        <li style="Margin-top: 0;Margin-bottom: 0;Margin-left: 0;font-family: Ubuntu,sans-serif;"><span
                            class="font-ubuntu" style="text-decoration: inherit;"><span
                              style="text-decoration: inherit;">A&#233;roport d'arriv&#233;e: ICN</span></span>
                        </li>
                        <li style="Margin-top: 0;Margin-bottom: 0;Margin-left: 0;font-family: Ubuntu,sans-serif;"><span
                            class="font-ubuntu" style="text-decoration: inherit;"><span
                              style="text-decoration: inherit;">Date de
                              d&#233;part: 2022-03-23</span></span>
                        </li>
                        <li style="Margin-top: 0;Margin-bottom: 0;Margin-left: 0;font-family: Ubuntu,sans-serif;"><span
                            class="font-ubuntu" style="text-decoration: inherit;"><span
                              style="text-decoration: inherit;">Date d'arriv&#233;e: 2022-04-21</span></span>
                        </li>
                      </ul>
                      <h2 class="size-17"
                        style="Margin-top: 20px;Margin-bottom: 0;font-style: normal;font-weight: normal;color: #555;font-size: 17px;line-height: 26px;font-family: Ubuntu,sans-serif;"
                        lang="x-size-17"><span class="font-ubuntu" style="text-decoration: inherit;"><span
                            style="text-decoration: inherit;">Prix actuel du vol Etihad:</span></span>
                      </h2>
                      <p style="Margin-top: 16px;Margin-bottom: 0;">&nbsp;</p>
                      <p class="size-36"
                        style="mso-text-raise: 14px;Margin-top: 20px;Margin-bottom: 0;font-family: Ubuntu,sans-serif;font-size: 30px;line-height: 38px;text-align: center;"
                        lang="x-size-36"><span class="font-ubuntu" style="text-decoration: inherit;"><span
                            style="text-decoration: inherit;"><strong>"""+str(minimumfare)+"""CHF</strong></span></span>
                      </p>
                      <p class="size-17"
                        style="Margin-top: 20px;Margin-bottom: 0;font-family: Ubuntu,sans-serif;font-size: 17px;line-height: 26px;text-align: center;"
                        lang="x-size-17"><span class="font-ubuntu" style="text-decoration: inherit;"><span
                            style="text-decoration: inherit;">&nbsp;</span></span>
                      </p>
                      <p class="size-17"
                        style="Margin-top: 20px;Margin-bottom: 0;font-family: Ubuntu,sans-serif;font-size: 17px;line-height: 26px;text-align: left;"
                        lang="x-size-17"><span class="font-ubuntu" style="text-decoration: inherit;"><span
                            style="text-decoration: inherit;">&#201;volution par rapport au pr&#233;c&#233;dent
                            rapport:</span></span>
                      </p>
                      <h2 class="size-64" style="mso-text-raise: 25px;Margin-top: 20px;Margin-bottom: 0;font-style: normal;font-weight: normal;color: #555;font-size: 
44px;line-height: 50px;font-family: Times,Times New Roman,serif;text-align: center;" lang="x-size-64"><span
                          class="font-times" style="text-decoration: inherit;"><span
                            style="text-decoration: inherit;"><span
                              style="text-decoration: inherit;color: #f70019;">"""+tendancy+"""</span></span>
                        </span>
                      </h2>
                      <h2 class="size-17"
                        style="Margin-top: 16px;Margin-bottom: 0;font-style: normal;font-weight: normal;color: #555;font-size: 17px;line-height: 26px;font-family: Ubuntu,sans-serif;"
                        lang="x-size-17"><span class="font-ubuntu" style="text-decoration: inherit;"><span
                            style="text-decoration: inherit;">&#201;volution du prix de la concurrence:</span></span>
                      </h2>
                      <div style="font-size: 12px;font-style: normal;font-weight: normal;line-height: 19px;"
                        align="center">
                        <img class="gnd-corner-image gnd-corner-image-center gnd-corner-image-bottom"
                          style="border: 0;display: block;height: auto;width: 100%;max-width: 720px;" alt="" width="600"
                          src="cid:image1" />
                      </div>
                      <h2 class="size-17"
                        style="Margin-top: 16px;Margin-bottom: 0;font-style: normal;font-weight: normal;color: #555;font-size: 17px;line-height: 26px;font-family: Ubuntu,sans-serif;"
                        lang="x-size-17"><span class="font-ubuntu" style="text-decoration: inherit;"><span
                            style="text-decoration: inherit;">&#201;volution du prix du vol Etihad:</span></span>
                      </h2>
                      <div style="font-size: 12px;font-style: normal;font-weight: normal;line-height: 19px;"
                        align="center">
                        <img class="gnd-corner-image gnd-corner-image-center gnd-corner-image-bottom"
                          style="border: 0;display: block;height: auto;width: 100%;max-width: 720px;" alt="" width="600"
                          src="cid:image2" />
                      </div>
                      <p style="Margin-top: 16px;Margin-bottom: 20px;">&nbsp;</p>
                    </div>
                  </div>
                </div>
                <!--[if (mso)|(IE)]></td></tr></table><![endif]-->
              </div>
            </div>

            <div style="mso-line-height-rule: exactly;line-height: 20px;font-size: 20px;">&nbsp;</div>

          </div>
          <div style="line-height:40px;font-size:40px;" id="footer-spacing">&nbsp;</div>
        </td>
      </tr>
    </tbody>
  </table>
  <style type="text/css">
    @media (max-width:619px) {

      .email-flexible-footer .left-aligned-footer .column,
      .email-flexible-footer .center-aligned-footer,
      .email-flexible-footer .right-aligned-footer .column {
        max-width: 100% !important;
        text-align: center !important;
        width: 100% !important
      }

      .flexible-footer-logo {
        margin-left: 0px !important;
        margin-right: 0px !important
      }

      .email-flexible-footer .left-aligned-footer .flexible-footer__share-button__container,
      .email-flexible-footer .center-aligned-footer .flexible-footer__share-button__container,
      .email-flexible-footer .right-aligned-footer .flexible-footer__share-button__container {
        display: inline-block;
        margin-left: 5px !important;
        margin-right: 5px !important
      }

      .email-flexible-footer__additionalinfo--center {
        text-align: center !important
      }

      .email-flexible-footer .left-aligned-footer table,
      .email-flexible-footer .center-aligned-footer table,
      .email-flexible-footer .right-aligned-footer table {
        display: table !important;
        width: 100% !important
      }

      .email-flexible-footer .footer__share-button,
      .email-flexible-footer .email-footer__additional-info {
        margin-left: 20px;
        margin-right: 20px
      }
    }
  </style>
</body>

</html>
"""

part2 = MIMEText(html, 'html')

fp = open(imagesrc, 'rb')
msgImage = MIMEImage(fp.read())
fp.close()
fp = open(imagesrcethiad, 'rb')
msgImageetihadplot = MIMEImage(fp.read())
fp.close()
# Define the image's ID as referenced above
msgImage.add_header('Content-ID', '<image1>')
msg.attach(msgImage)
msgImageetihadplot.add_header('Content-ID', '<image2>')
msg.attach(msgImageetihadplot)

msg.attach(part2)

context = ssl.create_default_context()
with smtplib.SMTP(smtp_server, port) as server:
    server.ehlo()  # Can be omitted
    server.starttls(context=context)
    server.ehlo()  # Can be omitted
    server.login("api@hfamily.ch", password)
    server.sendmail("api@hfamily.ch", ["hediger.yassin@gmail.com"], msg.as_string())